const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Turret,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Spawn: 0},
	{Speed: 0},
	{SpeedBeachFront: 0},
	{Enemy1Number: 0},
	{RespawnRate: 0},
	{Enemy1: 0},
	{DirectionCHange: 0},
	{Change_Direction_UP: 0},
	{Angle_UP_or_Down: 0},
	{Change_Direction_Right: 0},
	{Beachfront: 0},
	{EnemyCounter: 0},
	{ChangeDirectionUpOrLeft: 0},
	{TurnSound: 0},
	{Turret: 0},
	{Cannon: 0},
	{DestroyOutside: 0},
	{Bullet: 0},
	{Cannon_Ball: 0},
	{Cannon_Point: 0},
	{Mouse: 0},
	{GoldValue: 0},
	{SoundPlayed: 0},
	{Gold: 0},
	{wood: 0},
	{Explosion: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Spawn: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	Change_Direction_UP: class extends self.ISpriteInstance {},
	Angle_UP_or_Down: class extends self.ISpriteInstance {},
	Change_Direction_Right: class extends self.ISpriteInstance {},
	Beachfront: class extends self.ISpriteInstance {},
	EnemyCounter: class extends self.ITextInstance {},
	ChangeDirectionUpOrLeft: class extends self.ISpriteInstance {},
	TurnSound: class extends self.IInstance {},
	Cannon: class extends self.ISpriteInstance {},
	Cannon_Ball: class extends self.ISpriteInstance {},
	Cannon_Point: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Gold: class extends self.ITextInstance {},
	wood: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {}
}